using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OrderProcessing.Models
{  
    public class Order
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }  //primary key, not autogenerated

        [Required]
        [Display(Name="Customer Name")]
        public int CustomerID { get; set; }  //foreign key

        [Required]
        [Display(Name = "Product")]
        public int ProductID { get; set; }  //foreign key

        [Required]
        [Display(Name = "SalesPerson")]

        public int EmployeeID { get; set; }  //foreign key

        [DataType(DataType.Date)]
        [Display(Name = "Order Date")]
        public DateTime OrderDate { get; set; }

        [Range(1, 50)]
        public int Quantity { get; set; }

        public Customer Customer { get; set; }  //navigation property

        public Product Product { get; set; }  //navigation property

        public Employee Employee { get; set; }  //nav property
    }
}
